src/objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>AvailableQuantity__c</fullName>
        <label>Available Quantity</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.apex/src/objects/Purchase__c.object
<CustomObject>
    <fields>
        <fullName>ClientId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ClientId</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Purchases</relationshipLabel>
        <relationshipName>Purchases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Purchase</label>
    <nameField>
        <label>Purchase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PurchaseLine__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ItemId__c</fullName>
        <label>ItemId</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Purchase Lines</relationshipLabel>
        <relationshipName>Purchase_Lines</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PurchaseId__c</fullName>
        <label>PurchaseId</label>
        <referenceTo>Purchase__c</referenceTo>
        <relationshipLabel>Purchase Lines</relationshipLabel>
        <relationshipName>Purchase_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>UnitCost__c</fullName>
        <label>Unit Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Purchase Line</label>
    <nameField>
        <displayFormat>PL-{00000}</displayFormat>
        <label>Purchase Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CheckoutController.cls
public with sharing class CheckoutController {

	@AuraEnabled
	public static Id checkout(
			Id accountId,
			List<CartItemWrapper> cartItems
			) {

		List<Id> itemIds = new List<Id>();

		for (CartItemWrapper item : cartItems) {
			itemIds.add(item.itemId);
		}

		List<Item__c> items = [
				SELECT Id,
						Name,
						Price__c,
						AvailableQuantity__c
				FROM Item__c
				WHERE Id IN :itemIds
				FOR UPDATE
		];


		Map<Id, Item__c> itemMap = new Map<Id, Item__c>();

		for (Item__c item : items) {
			itemMap.put(item.Id, item);
		}


		for (CartItemWrapper cartItem : cartItems) {

			Item__c item = itemMap.get(cartItem.itemId);

			if (item.AvailableQuantity__c < cartItem.amount) {

				throw new AuraHandledException(
								'Not enough quantity for ' + item.Name
				);

			}
		}


		Purchase__c purchase = new Purchase__c(
				ClientId__c = accountId
		);

		insert purchase;


		List<PurchaseLine__c> lines = new List<PurchaseLine__c>();

		List<Item__c> updateItems = new List<Item__c>();


		for (CartItemWrapper cartItem : cartItems) {

			Item__c item = itemMap.get(cartItem.itemId);

			lines.add(
					new PurchaseLine__c(
							PurchaseId__c = purchase.Id,
							ItemId__c = item.Id,
							Amount__c = cartItem.amount,
							UnitCost__c = item.Price__c
					)
			);


			item.AvailableQuantity__c -= cartItem.amount;
			updateItems.add(item);
		}


		update updateItems;

		insert lines;


		return purchase.Id;
	}


	public class CartItemWrapper {

		@AuraEnabled
		public Id itemId {get;set;}

		@AuraEnabled
		public Integer amount {get;set;}

	}
}