src/objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>AvailableQuantity__c</fullName>
        <label>Available Quantity</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>Laptop</fullName>
                </value>
                <value>
                    <fullName>Tablet</fullName>
                </value>
                <value>
                    <fullName>Accessory</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <label>Image</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Electronic</fullName>
                </value>
                <value>
                    <fullName>Furniture</fullName>
                </value>
                <value>
                    <fullName>Food</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.apex/src/objects/Purchase__c.object
<CustomObject>
    <fields>
        <fullName>ClientId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ClientId</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Purchases</relationshipLabel>
        <relationshipName>Purchases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Purchase</label>
    <nameField>
        <label>Purchase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PurchaseLine__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ItemId__c</fullName>
        <label>ItemId</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Purchase Lines</relationshipLabel>
        <relationshipName>Purchase_Lines</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PurchaseId__c</fullName>
        <label>PurchaseId</label>
        <referenceTo>Purchase__c</referenceTo>
        <relationshipLabel>Purchase Lines</relationshipLabel>
        <relationshipName>Purchase_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>UnitCost__c</fullName>
        <label>Unit Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Purchase Line</label>
    <nameField>
        <displayFormat>PL-{00000}</displayFormat>
        <label>Purchase Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CheckoutControllerTest.cls
@IsTest
private class CheckoutControllerTest {

	@TestSetup
	static void setupData() {

		Account acc = new Account(
				Name = 'Test Account'
		);
		insert acc;


		Item__c item = new Item__c(
				Name = 'Test Laptop',
				Description__c = 'Test item',
				Family__c = 'Laptop',
				Type__c = 'Electronic',
				Price__c = 1000,
				AvailableQuantity__c = 5,
				Image__c = 'https://example.com/image.jpg'
		);
		insert item;
	}


	@IsTest
	static void testCheckoutCreatesPurchase() {

		Account acc = [
				SELECT Id
				FROM Account
				LIMIT 1
		];

		Item__c item = [
				SELECT Id, AvailableQuantity__c
				FROM Item__c
				LIMIT 1
		];


		CheckoutController.CartItemWrapper wrapper =
				new CheckoutController.CartItemWrapper();

		wrapper.itemId = item.Id;
		wrapper.amount = 2;


		List<CheckoutController.CartItemWrapper> cart =
				new List<CheckoutController.CartItemWrapper>();

		cart.add(wrapper);


		Test.startTest();

		Id purchaseId = CheckoutController.checkout(
				acc.Id,
				cart
		);

		Test.stopTest();


		Purchase__c purchase = [
				SELECT Id, ClientId__c
				FROM Purchase__c
				WHERE Id = :purchaseId
		];


		System.assertEquals(
				acc.Id,
				purchase.ClientId__c
		);


		PurchaseLine__c line = [
				SELECT Amount__c, UnitCost__c, ItemId__c
				FROM PurchaseLine__c
				WHERE PurchaseId__c = :purchaseId
		];


		System.assertEquals(
				2,
				line.Amount__c
		);


		System.assertEquals(
				1000,
				line.UnitCost__c
		);


		Item__c updatedItem = [
				SELECT AvailableQuantity__c
				FROM Item__c
				WHERE Id = :item.Id
		];


		System.assertEquals(
				3,
				updatedItem.AvailableQuantity__c
		);
	}


	@IsTest
	static void testCheckoutFailsWhenNotEnoughQuantity() {

		Account acc = [
				SELECT Id
				FROM Account
				LIMIT 1
		];

		Item__c item = [
				SELECT Id
				FROM Item__c
				LIMIT 1
		];

		CheckoutController.CartItemWrapper wrapper =
				new CheckoutController.CartItemWrapper();

		wrapper.itemId = item.Id;
		wrapper.amount = 100;


		List<CheckoutController.CartItemWrapper> cart =
				new List<CheckoutController.CartItemWrapper>();

		cart.add(wrapper);


		Test.startTest();

		Boolean exceptionThrown = false;

		try {

			CheckoutController.checkout(
					acc.Id,
					cart
			);

		} catch (AuraHandledException e) {

			exceptionThrown = true;

		}

		Test.stopTest();


		System.assertEquals(
				true,
				exceptionThrown
		);
	}
}