src/objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>AvailableQuantity__c</fullName>
        <label>Available Quantity</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>Laptop</fullName>
                </value>
                <value>
                    <fullName>Tablet</fullName>
                </value>
                <value>
                    <fullName>Accessory</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <label>Image</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Electronic</fullName>
                </value>
                <value>
                    <fullName>Furniture</fullName>
                </value>
                <value>
                    <fullName>Food</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ItemImageControllerTest.cls
@IsTest
private class ItemImageControllerTest {

	private class UnsplashMock implements HttpCalloutMock {

		public HTTPResponse respond(HTTPRequest request) {

			HttpResponse response = new HttpResponse();

			response.setStatusCode(200);

			response.setBody(
							'{' +
							'"results": [' +
							'{' +
							'"urls": {' +
							'"small": "https://images.unsplash.com/test-image.jpg"' +
							'}' +
							'}' +
							']' +
							'}'
			);

			return response;
		}
	}


	@IsTest
	static void testUpdateItemImage() {

		Item__c item = new Item__c(
				Name = 'iMac',
				Family__c = 'Laptop',
				Type__c = 'Electronic',
				Price__c = 1500,
				AvailableQuantity__c = 5
		);

		insert item;


		Test.setMock(
						HttpCalloutMock.class,
				new UnsplashMock()
		);


		Test.startTest();

		ItemImageController.updateItemImage(
				item.Id
		);

		Test.stopTest();


		Item__c updatedItem = [
				SELECT Image__c
				FROM Item__c
				WHERE Id = :item.Id
		];


		System.assertEquals(
				'https://images.unsplash.com/test-image.jpg',
				updatedItem.Image__c
		);
	}
}